//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyncBrowserClient.minidsgnsvc {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://example.com/sample.wsdl", ConfigurationName="minidsgnsvc.my_dispatcherPortType")]
    public interface my_dispatcherPortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8008/Open", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int Open(string url);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface my_dispatcherPortTypeChannel : SyncBrowserClient.minidsgnsvc.my_dispatcherPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class my_dispatcherPortTypeClient : System.ServiceModel.ClientBase<SyncBrowserClient.minidsgnsvc.my_dispatcherPortType>, SyncBrowserClient.minidsgnsvc.my_dispatcherPortType {
        
        public my_dispatcherPortTypeClient() {
        }
        
        public my_dispatcherPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public my_dispatcherPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public my_dispatcherPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public my_dispatcherPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Open(string url) {
            return base.Channel.Open(url);
        }
    }
}
